######################################################################
##
## Filename: p4ej3_tb.udo
## Created on: Wed Dec 07 12:19:29 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
