######################################################################
##
## Filename: P1EJ4a_tb.udo
## Created on: Thu Oct 13 11:51:25 Hora de verano romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
