######################################################################
##
## Filename: p3ej1b_tb.udo
## Created on: Fri Nov 11 10:52:24 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
