######################################################################
##
## Filename: p2ej2_montaje_tb.udo
## Created on: Mon Oct 31 13:50:41 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
