######################################################################
##
## Filename: p3ej2b_tb.udo
## Created on: Fri Nov 11 12:41:46 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
