######################################################################
##
## Filename: p2ej1_tb.udo
## Created on: Wed Oct 26 11:44:55 Hora de verano romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
