######################################################################
##
## Filename: p2ej2_tb.udo
## Created on: Wed Oct 26 12:05:08 Hora de verano romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
