######################################################################
##
## Filename: p4ej1_tb.udo
## Created on: Wed Nov 23 12:46:43 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
