######################################################################
##
## Filename: p4ej2_tb.udo
## Created on: Wed Nov 30 12:36:14 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
