######################################################################
##
## Filename: CircuitoTb.udo
## Created on: Wed Sep 21 12:24:34 Hora de verano romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
