######################################################################
##
## Filename: p3ej3_tb.udo
## Created on: Wed Nov 16 11:28:40 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
