######################################################################
##
## Filename: P1EJ1_tb.udo
## Created on: Fri Oct 14 10:54:45 Hora de verano romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
